### ISSUE TITLE
Comments about introduction

### ISSUE THREAD

**Issue by momdo** [studiomohawk/browserify-handbook#1]
私自身、Nodeはおろかjsもよく分かってないへっぽこなので、実は訳が根本的に間違っている可能性がありますが、私ならこう読めるかなぁということで。
適当に取捨選択してお使いください。

This document covers how to use browserify to build modular applications.
このドキュメントでは、browserifyを使ったモジュール・アプリケーションの作り方について紹介します。

browserify is a tool for compiling node-flavored commonjs modules for the browser.
browserifyは、ブラウザ用のNode風なCommonJSモジュールをコンパイルするためのツールです。

You can use browserify to organize your code and use third-party libraries even if you don't use node itself in any other capacity except for bundling and installing packages with npm.
npmを使ってパッケージをバンドルおよびインストールする以外は、たとえNodeそのものを利用していなくても、browserifyを利用することで、自分のコードや第三者が作成したライブラリを構造化することができるようになります。

The module system that browserify uses is the same as node, so packages published to npm that were originally intended for use in node but not browsers will work just fine in the browser too.
browserifyのモジュール・システムはNodeのものと同じです。そのため、ブラウザ用ではなくNodeで利用されることを元々想定している、npmで公開されているパッケージであっても、ブラウザで動作させることができます。

Increasingly, people are publishing modules to npm which are intentionally designed to work in both node and in the browser using browserify and many packages on npm are intended for use in just the browser.  npm is for all javascript, front or backend alike.
人々は徐々にNodeとbrowserifyを利用するブラウザの両方で意図的に動作するように設計されたモジュールをnpmに公開していますが、npm上の多くのパッケージはブラウザ専用のものです。フロントエンドもバックエンドも関係なく、npmはすべてのJavaScriptのためのものです。

**Comment by studiomohawk** [comment]
早速ありがとうございます!

**Comment by studiomohawk** [comment]
https://github.com/studiomohawk/browserify-handbook/commit/27d12df86bef248903e8a2629d18c0a9eebd657e 
にていただきました修正を反映いたしました。
